const fieldLabels = {
  DIVN: { label: "Divn" },
  MSTAE: { label: "Mstae" },
  STS: { label: "Sts" },
  TYP: { label: "Typ" },
  AUART: { label: "Auart" },
  MRPI: { label: "Mrpi" },
  MFGPL: { label: "Mfgpl" },
  CREATOR: { label: "Creator" },
  CUSTNO: { label: "Custno" },
  CUSTOMER: { label: "Customer" },
  ORDER_NO: { label: "Order No", required: true },
  ITEM_NO: { label: "Item No",required: true },
  MATL_NO: { label: "Matl No" },
  DESCRIPTION: { label: "Description" },
  FINPO: { label: "Finpo" },
  INTPO: { label: "Intpo" },
  CDRW: { label: "Cdrw" },
  MILL: { label: "Mill" },
  CTG: { label: "Ctg" },
  SPEC: { label: "Spec" },
  SFIN: { label: "Sfin" },
  OD: { label: "Od" },
  THK: { label: "Thk" },
  LENGTH: { label: "Length" },
  CLASS: { label: "Class" },
  GEOMETRY: { label: "Geometry" },
  IN_DIA: { label: "In Dia" },
  ORDQ: { label: "Ordq" },
  ORDUM: { label: "Ordum" },
  ORDNOS: { label: "Ordnos" },
  ORDTONS: { label: "Ordtons" },
  MILLNOS: { label: "Millnos" },
  MILLTONS: { label: "Milltons" },
  NRMLNOS: { label: "Nrmlnos" },
  NRMLTONS: { label: "Nrmltons" },
  INSPNOS: { label: "Inspnos" },
  INSPTONS: { label: "Insptons" },
  TRFRNOS: { label: "Trfrnos" },
  TRFRTONS: { label: "Trfrtons" },
  DESPNOS: { label: "Despnos" },
  BRCHQ: { label: "Brchq" },
  LTRFRDT: { label: "Ltrfrdt" },
  LDESPDT: { label: "Ldespdt" },
  HOLLOW: { label: "Hollow" },
  STEEL: { label: "Steel" },
  OD_H: { label: "Od H" },
  THK_H: { label: "Thk H" },
  LGTH_H: { label: "Lgth H" },
  CATG_S: { label: "Catg S" },
  WIDTH_S: { label: "Width S" },
  THK_S: { label: "Thk S" },
  SFIN_S: { label: "Sfin S" },
  ORDSTS: { label: "Ordsts" },
  ITMSTS: { label: "Itmsts" },
  SCHSTS: { label: "Schsts" },
  PRMSDATE: { label: "Prmsdate" },
  MESSAGE: { label: "Message" },
  PINO: { label: "Pino" },
  PGRP: { label: "Pgrp" },
  CCR: { label: "Ccr" },
  ORDLOAD: { label: "Ordload" },
  AMOUNT: { label: "Amount" },
  BOILER_UNIT: { label: "Boiler Unit" },
  REQUISITIONER: { label: "Requisitioner" },
  TRACKING_NO: { label: "Tracking No" },
  KGNONUM: { label: "Kgnonum" },
  KGNODEN: { label: "Kgnoden" },
  SOBSL: { label: "Sobsl" },
  FINPLO: { label: "Finplo" },
  INTPLO: { label: "Intplo" },
  VERID: { label: "Verid" },
  CNFRMDT: { label: "Cnfrmdt" },
  CUSTOMER_F: { label: "Customer F" },
};

export default fieldLabels;
